default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
#  username: <%= ENV['POSTGRES_USER'] %>
#  password: <%= ENV['POSTGRES_PASSWORD'] %>
#  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  host: localhost
  database: security_assignment_development

test:
  <<: *default
  database: security_assignment_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
